public  class AdocaoBO {

    public static void envioEmailAguardandoBuscaPet(List<Adocao__c> adList){

        /*Contact contato;

        for(Adocao__c adocao : adList){
            
            if(adocao.Status__c == 'Aguardando busca do pet')
                if(adocao.Contact__c != null)
                    contato = ContactDAO.getContactById(adocao.Contact__c);
            
            if(contato.Email != null)
                EmailService.enviarEmailBuscarPet(contato);
        }*/
    }
}
